const GET_SELLER = "GET_SELLER";
const GET_GOODS = "GET_GOODS";
const GET_RATINGS = "GET_RATINGS";
const SHOW_DETAIL = "SHOW_DETAIL";
const HIDE_DETAIL = "HIDE_DETAIL";

export default {
  GET_SELLER,
  GET_GOODS,
  GET_RATINGS,
  SHOW_DETAIL,
  HIDE_DETAIL
}
